# Generated by Django 5.0.6 on 2024-11-22 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_initial_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='property_type',
            field=models.CharField(choices=[('Apartment', 'Apartment'), ('House', 'House'), ('Hotel', 'Hotel'), ('Studio', 'Studio'), ('Villa', 'Villa'), ('Cabin', 'Cabin'), ('Loft', 'Loft'), ('Penthouse', 'Penthouse'), ('Cottage', 'Cottage')], max_length=50),
        ),
    ]
